# Generated by Django 3.1.1 on 2020-10-08 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20201008_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='uni',
        ),
    ]
