# Generated by Django 3.1.1 on 2020-10-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieRecom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='imbdid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='links',
            name='tmdbid',
            field=models.IntegerField(),
        ),
    ]
