# Generated by Django 3.1.1 on 2020-10-23 21:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movieRecom', '0003_ratings'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ratings',
            unique_together={('user', 'movieid')},
        ),
    ]
